[workspace]
resolver = "2"
members = [
    "routedroid",
    "routedroidd",
    "routedroid-ipc",
    "routedroid-tui",
    "routedroid-proto",
    "routedroid-helper-ipc",
    "routedroid-dhcp",
    "routedroid-helper",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
